<a href="https://colab.research.google.com/github/Amon52/Amon/blob/main/Classifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
train_data=pd.read_csv("train.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S



1.   Removing Items that may not have an impact on our model

*   PassengerId
*   Name


*   Ticket
*   Cabin number

In [8]:
train_data.drop(['PassengerId','Name','Ticket','Cabin'],axis=1,inplace=True)
train_data.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [10]:
train_data.dtypes

Survived      int64
Pclass        int64
Sex          object
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Embarked     object
dtype: object

In [11]:
train_data=pd.get_dummies(train_data,drop_first=True, dtype = int)

In [12]:
train_data

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,1,0,1
1,1,1,38.0,1,0,71.2833,0,0,0
2,1,3,26.0,0,0,7.9250,0,0,1
3,1,1,35.0,1,0,53.1000,0,0,1
4,0,3,35.0,0,0,8.0500,1,0,1
...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,1,0,1
887,1,1,19.0,0,0,30.0000,0,0,1
888,0,3,NaN,1,2,23.4500,0,0,1
889,1,1,26.0,0,0,30.0000,1,0,0
890,0,3,32.0,0,0,7.7500,1,1,0

In [15]:
train_data.isnull().sum()

Survived        0
Pclass          0
Age           177
SibSp           0
Parch           0
Fare            0
Sex_male        0
Embarked_Q      0
Embarked_S      0
dtype: int64

In [16]:
train_data['Age']=train_data['Age'].fillna(train_data['Age'].median())

In [17]:
train_data.isnull().sum()

Survived      0
Pclass        0
Age           0
SibSp         0
Parch         0
Fare          0
Sex_male      0
Embarked_Q    0
Embarked_S    0
dtype: int64

**Training The model**

In [20]:
from sklearn.model_selection import train_test_split
### target and the predictors
ml_data=train_data.copy()
X=ml_data.drop(columns=["Survived"])
y=ml_data["Survived"]

#training set and testing set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=42)

print(f"training X:{X_train.shape} Y:{y_train.shape}")
print(f"training X:{X_test.shape} Y:{y_test.shape}")

training X:(712, 8) Y:(712,)
training X:(179, 8) Y:(179,)

In [24]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(X_train,y_train)

y_prediction=dtc.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

accuracy=accuracy_score(y_test,y_prediction)
confusion_matrix=confusion_matrix(y_test,y_prediction)

print(f"Accuracy:{accuracy}")
print(f"Confusion Matrix:{confusion_matrix}")

Accuracy:0.7877094972067039
Confusion Matrix:[[86 19]
 [19 55]]