<a href="https://colab.research.google.com/github/Amon52/Amon/blob/main/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data=pd.read_excel(r"Concrete_Data.xls")
data.head()

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),"Concrete compressive strength(MPa, megapascals)"
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [3]:
data.columns

Index(['Cement (component 1)(kg in a m^3 mixture)',
       'Blast Furnace Slag (component 2)(kg in a m^3 mixture)',
       'Fly Ash (component 3)(kg in a m^3 mixture)',
       'Water  (component 4)(kg in a m^3 mixture)',
       'Superplasticizer (component 5)(kg in a m^3 mixture)',
       'Coarse Aggregate  (component 6)(kg in a m^3 mixture)',
       'Fine Aggregate (component 7)(kg in a m^3 mixture)', 'Age (day)',
       'Concrete compressive strength(MPa, megapascals) '],
      dtype='object')

**Objective:** To come up with ML model that can predict Concrete compressive Strenght

In [4]:
data.dtypes

Cement (component 1)(kg in a m^3 mixture)                float64
Blast Furnace Slag (component 2)(kg in a m^3 mixture)    float64
Fly Ash (component 3)(kg in a m^3 mixture)               float64
Water  (component 4)(kg in a m^3 mixture)                float64
Superplasticizer (component 5)(kg in a m^3 mixture)      float64
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     float64
Fine Aggregate (component 7)(kg in a m^3 mixture)        float64
Age (day)                                                  int64
Concrete compressive strength(MPa, megapascals)          float64
dtype: object

In [6]:
from sklearn.model_selection import train_test_split
### target and the predictors
ml_data=data.copy()
X=ml_data.drop(columns=["Concrete compressive strength(MPa, megapascals) "])
y=ml_data["Concrete compressive strength(MPa, megapascals) "]

#training set and testing set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=42)

print(f"training X:{X_train.shape} Y:{y_train.shape}")
print(f"training X:{X_test.shape} Y:{y_test.shape}")

training X:(824, 8) Y:(824,)
training X:(206, 8) Y:(206,)

In [7]:
#Training a Linear regression model
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)
y_predictions=lr.predict(X_test)

**Model Evaluation**

In [14]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

r2=r2_score(y_test,y_predictions)
mse=mean_squared_error(y_test,y_predictions)
mae=mean_absolute_error(y_test,y_predictions)

print(f"R^2 : {r2} \n mse: {mse} \n mae: {mae}")

R^2 : 0.627541605542902
 mse: 95.97548435337708
 mae: 7.745392872421345

In [20]:
#Training a Decision Tree regression model
from sklearn.tree import DecisionTreeRegressor
lr=DecisionTreeRegressor()
lr.fit(X_train,y_train)
y_predictions=lr.predict(X_test)

In [21]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

r2=r2_score(y_test,y_predictions)
mse=mean_squared_error(y_test,y_predictions)
mae=mean_absolute_error(y_test,y_predictions)

print(f"R^2 : {r2} \n mse: {mse} \n mae: {mae}")

R^2 : 0.8071400405320641
 mse: 49.696364205425084
 mae: 4.558473442923023

In [24]:
class DecisionTreeRegressor():

SyntaxError: incomplete input (836416953.py, line 1)

In [25]:
#Training a Linear regression model
from sklearn.ensemble import RandomForestRegressor
lr=RandomForestRegressor()
lr.fit(X_train,y_train)
y_predictions=lr.predict(X_test)

In [26]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

r2=r2_score(y_test,y_predictions)
mse=mean_squared_error(y_test,y_predictions)
mae=mean_absolute_error(y_test,y_predictions)

print(f"R^2 : {r2} \n mse: {mse} \n mae: {mae}")

R^2 : 0.8782521703538464
 mse: 31.372113216280226
 mae: 3.8104284823725108

In [ ]:
#Training a Linear regression model
from sklearn.ensemble import RandomForestRegressor
lr=RandomForestRegressor()
lr.fit(X_train,y_train)
y_predictions=lr.predict(X_test)